name: user_list_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  sqflite: ^2.3.0
  path: ^1.8.3
  get_it: ^7.6.4
  dartz: ^0.10.1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.3
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
